ALTER TABLE "Agreement" ADD COLUMN IF NOT EXISTS "creatorMoveInAck" BOOLEAN NOT NULL DEFAULT false;
ALTER TABLE "Agreement" ADD COLUMN IF NOT EXISTS "otherMoveInAck" BOOLEAN NOT NULL DEFAULT false;
ALTER TABLE "Agreement" ADD COLUMN IF NOT EXISTS "moveInConfirmedAt" TIMESTAMP(3);
